---
- name: Cleanup
  hosts: all
  gather_facts: True

  roles:
    - role: cloudnonsense.portainer
      vars:
        portainer_state: absent

  post_tasks:
    - name: Remove all unnamed (dangling) Docker volumes
      ansible.builtin.command: docker volume prune -f
      changed_when: "'Total reclaimed space' in prune_result.stdout"
      register: prune_result
...