---

- name: Prepare
  hosts: all
  gather_facts: True

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Python & deps
      apt:
        name:
          - python3
          - python3-apt
        state: present
        update_cache: yes

  roles:
    - role: geerlingguy.docker
      vars:
        # without this, the geerlingguy.docker role
        # attempts to start the docker systemd service.
        docker_service_manage: false

...